version: '3'
services:
  bullboard:
    container_name: bullboard
    image: venatum/bull-board
    restart: always
    ports:
      - 3001:3000
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379